Repository etalab/geo.data.gouv.fr, pull requests merged in 2018-07, with the labels that each got.

#653 Move workshop 9 to past events
  pages/events.js
Labels: enhancement

#652 Start map feature ids at 1
  components/centered-map/enhance-map-data.js
Labels: bug

#649 Display entire france for empty datasets
  __tests__/lib/geo/bbox.js
  components/centered-map/empty.js
  components/centered-map/enhance-map-data.js
  components/centered-map/map.js
  components/dataset/spatial-extent.js
  lib/geo/bbox.js
  locales/en/common.json
  locales/fr/common.json
Labels: bug

#654 Update eslint dependencies and fix errors
  components/hoc/with-fetch.js
  components/modal.js
  components/publication/datasets.js
  components/publication/organization/source-catalogs.js
  components/search-input.js
  package.json
  pages/publication/datasets.js
  pages/publication/organization.js
  pages/publication/producers.js
  pages/search.js
  yarn.lock
Labels: cleanup, dependencies
